### ISSUE TITLE
What is z_mod_P?

### ISSUE THREAD

**Issue by KodywithaK** [MedicalMess0001/UnrealPackManager#1]
> Could not find a part of the path
> "<Output_Directory>\z_mod_P"

Happens after dragging my .utoc/.ucas onto the `Unpack` button

**Comment by MedicalMess0001** [comment]
z_mod_p is what the name of the .utoc/.ucas would be during output not sure why you are getting that error. as long as your .utoc/.ucas are both in the same location you only need to drag one of them it will grab the other one.  


After defining your output directory you could create a folder in there with that name and see if that issue persists. it usually does it when the output folder is given and that would be the folder you zip to do other things with or throw into your game for organizing purposes. try making a folder with that name inside your output folder and try again. also its been a while since i worked on this so i cant remember if this was the most up to date or if the one on nexus was ill have to check.

**Comment by KodywithaK** [comment]
After trying out a few different games, I think it may be a .utoc that UEcastoc doesn't support yet, after seeing similar issues in that repository's issues section.
*****
I opened up a windows sandbox and placed UPM's + UEcastoc's + my output folders and 2 pairs of .utoc+.ucas on the desktop of it.
- \<game1\> is unencrypted, and just released within the past month.
- \<game2\> is encrypted, and released around a year ago now.
  - I don't know the UE versions of either at the moment.
*****
After dropping the UEcastoc's main.exe & my output folder & \<game1\>.utoc to their points on the UI, it runs as intended (despite logging `Warning: this is a version of the utoc file format that may not be supported yet`) and creates:
- \<output_dir\>\z_mod_P\\<game1\>
- \<output_dir\>\z_mod_P\Engine
- \<output_dir\>\manifest.json
  - however, the inside only contains `null`
*****
But when I try to unpack \<game2\>:

the command prompt either crashes
- instantly, if "\<output_dir\>\z_mod_P\\" is present
- after a few seconds, if "\<output_dir\>\z_mod_P\\" is missing
  - if I delete/rename the z_mod_P folder or start out fresh with a new sandbox.<br><br>
- This happens regardless of if I input the correct AES key or leave the area blank.

Then creates "\<output_dir\>\manifest.json"
- however, the inside only contains `null`

**Comment by MedicalMess0001** [comment]
that is a possible since this is just adding a UI to that tool that would normally require a command line to work. ive talked with Menv when i first made this about a few things but i am unsure how much work if any they have or will be putting into main.exe. as some issues were there and i fixed a few in the background of this tool. while yes you can use main.exe and a command line alone any further modifications to that utoc and ucas will have issues and this tool fixes the issues along the way but i have found other issues which menv was working on the last i spoke to them a few months ago.
